schema = 3

[mod]
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.3.0"
    hash = "sha256-hj2Xjlz3vj7KYONZO/ItclWGGJEUgo5EvMEkGPfQi1Q="
  [mod."filippo.io/edwards25519"]
    version = "v1.1.0"
    hash = "sha256-9ACANrgWZSd5HYPfDZHY8DVbPSC9LOMgy8deq3rDOoc="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.3.0"
    hash = "sha256-fBG3nuxEW+0fRHegSzj7q4GyEMCINeOUbkfqFG2cU+8="
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.6.2"
    hash = "sha256-tVNWDUMILZbJvarcl/E7tpSnkn7urqgSHa2Eaka5vSU="
  [mod."github.com/akutz/memconn"]
    version = "v0.1.0"
    hash = "sha256-WOs/RQYjQbn41ui8ztHgWSd4jxydE+fvIrl/0dmHD9Y="
  [mod."github.com/alexbrainman/sspi"]
    version = "v0.0.0-20231016080023-1a75b4708caa"
    hash = "sha256-Joa/NfBofK7lRlknQ5LVYD4M/dpd9xaCqsvYUBhKW0I="
  [mod."github.com/anmitsu/go-shlex"]
    version = "v0.0.0-20200514113438-38f4b401e2be"
    hash = "sha256-L3Ak4X2z7WXq7vMKuiHCOJ29nlpajUQ08Sfb9T0yP54="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.36.0"
    hash = "sha256-j1XPvTErqlSE8iJzi3nZPeDV8oOt+UWhRuK7TyJwIK8="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.29.5"
    hash = "sha256-xDBYnATFgBgSuPPHKyvXIiIDavT0toMRN/KYXnKzTvU="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.17.58"
    hash = "sha256-rjk+RnGf50icQDY+NzLhRkkBe5JZ/l2MUQAA7403bNo="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.16.27"
    hash = "sha256-VZwB0vXDjJ/+p9OPNAJ3nZEVFHiU2O27Kn/SESB5ZQM="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.3.31"
    hash = "sha256-kBgmVyB5UsAILeRMjvE94eTLpwsLtTRa3ghI3kwuk7g="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.6.31"
    hash = "sha256-l57uNlVYhm+7rMulQGDsdBFqccm7b2RIBjXdnFew4ZY="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.8.2"
    hash = "sha256-B2j5VassSR24lT1Sx6ZFSGFwwitmFntgeIeE+6FBNcg="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.12.2"
    hash = "sha256-zNvYlSlLD8RLEKoVteDx0ilLO03eS/gmgn4qb1ztLas="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.12.12"
    hash = "sha256-jFpAWhcHAsjtrVu1llf1QMAQ2fSObQNprr15EiciCnA="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssm"]
    version = "v1.44.7"
    hash = "sha256-U7XGN5O0Ksp6O3a2Nkb0WinTwuIHjCw5UNSwPjrMo8k="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.24.14"
    hash = "sha256-hf2KPjzO2fwohvT1FOoW/d46wu6r0TRnNERSQSBDlhk="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.28.13"
    hash = "sha256-2K9IhVPMC04jYGvD7fJQsRPUmFCw1qSCthVzK9NzBWA="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.33.13"
    hash = "sha256-J2Gwjo7TBn3WA6teGnkJRU9bRfYu7SE34YeJ2DZ3BpI="
  [mod."github.com/aws/smithy-go"]
    version = "v1.22.2"
    hash = "sha256-YdwVeW509cpqU357MjDM8ReL1vftkW8XIhSbJsbTh/s="
  [mod."github.com/coder/websocket"]
    version = "v1.8.12"
    hash = "sha256-jEaJSKcwmKtXFkvtxwpEdFMdazXZM6bY2u5TGBimklI="
  [mod."github.com/containerd/stargz-snapshotter/estargz"]
    version = "v0.16.3"
    hash = "sha256-HS4jUMc1whTwc0Cq0vzw9NoKUvrz7Qyjulne2Sayrhg="
  [mod."github.com/coreos/go-iptables"]
    version = "v0.7.1-0.20240112124308-65c67c9f46e6"
    hash = "sha256-kjnry8ld5Keew5q+tX7GSdGVZaXlehs2Lt+z8Rokhns="
  [mod."github.com/creack/pty"]
    version = "v1.1.23"
    hash = "sha256-42k7lObS5h99pPoicb6tkRlBvVvSPqsy+aC87PWq2o4="
  [mod."github.com/dblohm7/wingoes"]
    version = "v0.0.0-20240119213807-a09d6be7affa"
    hash = "sha256-zUj7jSZQiX53+4OyRq7LaQXp8nx8+JRpyT6IFdktyw0="
  [mod."github.com/digitalocean/go-smbios"]
    version = "v0.0.0-20180907143718-390a4f403a8e"
    hash = "sha256-Hgx1ML3rigdYXx5ntnEYD5JEk6kJv1cL0+/GDbnPkbo="
  [mod."github.com/distribution/reference"]
    version = "v0.6.0"
    hash = "sha256-gr4tL+qz4jKyAtl8LINcxMSanztdt+pybj1T+2ulQv4="
  [mod."github.com/docker/cli"]
    version = "v27.5.1+incompatible"
    hash = "sha256-95VkqBW6HDtyb3M50TriEBd9gwUSlz1HjG0lj/5cs6Y="
  [mod."github.com/docker/distribution"]
    version = "v2.8.3+incompatible"
    hash = "sha256-XhRURCGNpJC83QZTtgCxHHFL76HaxIxjt70HwUa847E="
  [mod."github.com/docker/docker"]
    version = "v27.5.1+incompatible"
    hash = "sha256-mF9CwasEIRYkOy1NW7EidF9SsUCCKKcLnMMhNV1FLM8="
  [mod."github.com/docker/docker-credential-helpers"]
    version = "v0.8.2"
    hash = "sha256-AmCyOKd6Xvz0BUZchGSJdbPolprne/pAmCr2UoXXRBE="
  [mod."github.com/docker/go-connections"]
    version = "v0.5.0"
    hash = "sha256-aGbMRrguh98DupIHgcpLkVUZpwycx1noQXbtTl5Sbms="
  [mod."github.com/docker/go-units"]
    version = "v0.5.0"
    hash = "sha256-iK/V/jJc+borzqMeqLY+38Qcts2KhywpsTk95++hImE="
  [mod."github.com/evanw/esbuild"]
    version = "v0.23.1"
    hash = "sha256-wK8lHEzyZvrNGBeYfxGhlzvbvGvSpgNbefZaW6rHn40="
  [mod."github.com/fatih/color"]
    version = "v1.18.0"
    hash = "sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.4"
    hash = "sha256-c1JKoRSndwwOyOxq9ddCe+8qn7mG9uRq2o/822x5O/c="
  [mod."github.com/fxamacker/cbor/v2"]
    version = "v2.7.0"
    hash = "sha256-ln5ms4UxxQ563bZ2UaNLG/bNsmohlgK18K+UUOyZNA0="
  [mod."github.com/gaissmai/bart"]
    version = "v0.18.0"
    hash = "sha256-YmefuPQoaaez/RyCLcgVns0M77RaTjs4ntvFbKRAdWw="
  [mod."github.com/go-json-experiment/json"]
    version = "v0.0.0-20250813024750-ebf49471dced"
    hash = "sha256-Fi2Gjw0cUGUSJ+RlcJXlQhk4jMTuut4pMENzkxcGm54="
  [mod."github.com/go-logr/logr"]
    version = "v1.4.2"
    hash = "sha256-/W6qGilFlZNTb9Uq48xGZ4IbsVeSwJiAMLw4wiNYHLI="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.1-0.20230522191255-76236955d466"
    hash = "sha256-OdcyeoGQ4xWUpl21WKXkbAm8yZHMDp8giY02arupjb4="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/google/btree"]
    version = "v1.1.2"
    hash = "sha256-K7V2obq3pLM71Mg0vhhHtZ+gtaubwXPQx3xcIyZDCjM="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/nftables"]
    version = "v0.2.1-0.20240414091927-5e242ec57806"
    hash = "sha256-OXMzx4Exf++E4UzCUE1gw3TOrfyI187cFu3cDZ9ifKU="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.3"
    hash = "sha256-vTIGEFMEi+30ZdO6ffMNJ/kId6pZs5bbyqov8xe9BM0="
  [mod."github.com/hdevalence/ed25519consensus"]
    version = "v0.2.0"
    hash = "sha256-KTbeKMOT/HCJjDHqyciQjJPPgpNk6H0VyQCCbeGgs7Y="
  [mod."github.com/hugomd/ascii-live"]
    version = "v0.0.0-20231008062449-0e53a4799f1e"
    hash = "sha256-0o+LuqyOscBKUr7fZXSF9UZoC/3Y4Q7DVZU9cZM4GgU="
  [mod."github.com/illarion/gonotify/v3"]
    version = "v3.0.2"
    hash = "sha256-g22zl/cA3It0Q2HrC7bm3U/9j94jHi8EUW8Svbyofh0="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jmespath/go-jmespath"]
    version = "v0.4.0"
    hash = "sha256-xpT9g2qIXmPq7eeHUXHiDqJeQoHCudh44G/KCSFbcuo="
  [mod."github.com/jsimonetti/rtnetlink"]
    version = "v1.4.0"
    hash = "sha256-GnrF2yxgm/h1JSTN1PwI4ysTl+oY0AyWzf3Ni7LZqRM="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.11"
    hash = "sha256-LFSIWy0C4VbiuPve0eKHr7Q7s4XtaGzsZ3qpO+6bEgc="
  [mod."github.com/kr/fs"]
    version = "v0.1.0"
    hash = "sha256-+Cjz0rGmdNIV1QL4z8h7JAjHATa5pKndwSnD1M0J74c="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mdlayher/genetlink"]
    version = "v1.3.2"
    hash = "sha256-pgwXkyDY1dlB8tmV1lQ0Bz/2g0zmJOyXvQjacACy924="
  [mod."github.com/mdlayher/netlink"]
    version = "v1.7.3-0.20250113171957-fbb4dce95f42"
    hash = "sha256-9sqFsrGRfJPCLiU/sLDWsiJwC+yOVojvB2cluq+x+dU="
  [mod."github.com/mdlayher/sdnotify"]
    version = "v1.0.0"
    hash = "sha256-O7MJt6Bam2bUoede07Z1T6EtW+kCJ+/4dJtYopZct1s="
  [mod."github.com/mdlayher/socket"]
    version = "v0.5.0"
    hash = "sha256-3zEbix66G+LQ2xAQW9XmkyubK9R+Vwnm09H5fqqLC7w="
  [mod."github.com/miekg/dns"]
    version = "v1.1.58"
    hash = "sha256-UGvyC1Abh2S5VaAUCV9AUuDMrCvpiWQy/UnYM9DfIB8="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/moby/docker-image-spec"]
    version = "v1.3.1"
    hash = "sha256-xwSNLmMagzywdGJIuhrWl1r7cIWBYCOMNYbuDDT6Jhs="
  [mod."github.com/moby/term"]
    version = "v0.5.0"
    hash = "sha256-jy0kbkeUsr0KoiE33WLxNAgYXZIERKR2O5+saXBwdD8="
  [mod."github.com/morikuni/aec"]
    version = "v1.0.0"
    hash = "sha256-5zYgLeGr3K+uhGKlN3xv0PO67V+2Zw+cezjzNCmAWOE="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0"
    hash = "sha256-5OxW1ShHypLpzVu+BJivNlFX2JFPh9WKfJcMIgPZf4U="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pkg/sftp"]
    version = "v1.13.6"
    hash = "sha256-x1dTv4M1hRc0wsbTe4wOCM8jdH/GWzI8ls5lm92nZVg="
  [mod."github.com/prometheus-community/pro-bing"]
    version = "v0.4.0"
    hash = "sha256-3TH0wB85OITw3uzTcEva2EcEF6jNf98sAoSOsnL2G9g="
  [mod."github.com/safchain/ethtool"]
    version = "v0.3.0"
    hash = "sha256-q5bQGHB7cyEejA9tQkrhpvzpfYRvXcmClbWBgfs3Ymc="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.3"
    hash = "sha256-EnxsWdEUPYid+aZ9H4/iMTs1XMvCLbXZRDyvj89Ebms="
  [mod."github.com/spf13/cobra"]
    version = "v1.9.1"
    hash = "sha256-dzEqquABE3UqZmJuj99244QjvfojS8cFlsPr/MXQGj0="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.6"
    hash = "sha256-NjrK0FZPIfO/p2xtL1J7fOBQNTZAPZOC6Cb4aMMvhxI="
  [mod."github.com/tailscale/certstore"]
    version = "v0.1.1-0.20231202035212-d3fa0460f47e"
    hash = "sha256-Q0HLTQPRsIizRqvdBBaLGoLascQiSpQm+X3NW3ytpDQ="
  [mod."github.com/tailscale/go-winio"]
    version = "v0.0.0-20231025203758-c4f33415bf55"
    hash = "sha256-WFW20c02gIk2MhafeVVNydmSfszPZegshDd2Y5abGgY="
  [mod."github.com/tailscale/goupnp"]
    version = "v1.0.1-0.20210804011211-c64d0f06ea05"
    hash = "sha256-PRMJcYY+wjpbHkC9dQWTPErh2ID29UnFxehxmYR704I="
  [mod."github.com/tailscale/hujson"]
    version = "v0.0.0-20221223112325-20486734a56a"
    hash = "sha256-q9c2IjwbL0IgYPznVpQP1XT/8lrzH1niI3E+wjNcf5Y="
  [mod."github.com/tailscale/netlink"]
    version = "v1.1.1-0.20240822203006-4d49adab4de7"
    hash = "sha256-ldPNC6TF8kY2OIHZvOPHcJLJrepTXZGP4wnxOq0rxH0="
  [mod."github.com/tailscale/peercred"]
    version = "v0.0.0-20250107143737-35a0c7bd7edc"
    hash = "sha256-m8Avdt5Y0G9xSf68Bznzc+lV5VOrdACBQaYF17vRk1E="
  [mod."github.com/tailscale/web-client-prebuilt"]
    version = "v0.0.0-20250124233751-d4cd19a26976"
    hash = "sha256-hcBR5fpJyukPgiDgRA9tItBAM/Y+iyRlrY2EW60kb3E="
  [mod."github.com/tailscale/wireguard-go"]
    version = "v0.0.0-20250716170648-1d0488a3d7da"
    hash = "sha256-pF5vpuqyWqYo86VIFfLQ9H5FreSXOTnRleoozh90l2U="
  [mod."github.com/vbatts/tar-split"]
    version = "v0.11.6"
    hash = "sha256-niIR0Yhe4EphEKb15L06uiCZfR/d6bdOnRXjhLdhKk4="
  [mod."github.com/vishvananda/netns"]
    version = "v0.0.5"
    hash = "sha256-wYDmrmqdv9R8dAL5nuWJ+1Nh7fWWxdpd03UkLOtyJrk="
  [mod."github.com/x448/float16"]
    version = "v0.8.4"
    hash = "sha256-VKzMTMS9pIB/cwe17xPftCSK9Mf4Y6EuBEJlB4by5mE="
  [mod."go.opentelemetry.io/auto/sdk"]
    version = "v1.1.0"
    hash = "sha256-cA9qCCu8P1NSJRxgmpfkfa5rKyn9X+Y/9FSmSd5xjyo="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.58.0"
    hash = "sha256-iqTPHfR1wXZY/yVTWtRBMjWlZkRxasaBGNhsNWHYxGw="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.33.0"
    hash = "sha256-NdAEEIqa81WLpDJbz4aCR4Ha/WnZcHPXY7d/jSu7H/k="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"]
    version = "v1.30.0"
    hash = "sha256-zQILxmK0vlE28y0KeM5LQYEZWrSfn8jrZ0Mg6M6arf8="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v1.33.0"
    hash = "sha256-bYr//1svQZ/uVWveaJGAxTpq0/rsFnDHKE6H2gVdce8="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.30.0"
    hash = "sha256-a+oojnlDDHnliphPvObLdW2jZjfSDcBF7QkV7H9ZltY="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.33.0"
    hash = "sha256-2bDa27eZT0+JHcDzV+MMCGKKYs7eYuTtGHIlbE0/gpk="
  [mod."go4.org/mem"]
    version = "v0.0.0-20240501181205-ae6ca9944745"
    hash = "sha256-GuSI6u7KRA6zHr/ZnWA2a24k2naETKBTpyB2A0NVS8A="
  [mod."go4.org/netipx"]
    version = "v0.0.0-20231129151722-fdeea329fbba"
    hash = "sha256-qFrVlacz5R3Lpkzqeg1/1MYew3DJzY9hG0Uh/ua+SOU="
  [mod."golang.org/x/crypto"]
    version = "v0.38.0"
    hash = "sha256-5tTXlXQBlfW1sSNDAIalOpsERbTJlZqbwCIiih4T4rY="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20250210185358-939b2ce775ac"
    hash = "sha256-3nIn0Ce1PFzVmVquJPN1vNwnyRtY3Zkx46affFb89Io="
  [mod."golang.org/x/mod"]
    version = "v0.24.0"
    hash = "sha256-Lrl4RzOO0J/S5E+AQ7Y6yh8B9yygvZ2W0fsKEtBSYNU="
  [mod."golang.org/x/net"]
    version = "v0.40.0"
    hash = "sha256-BhDOHTP8RekXDQDf9HlORSmI2aPacLo53fRXtTgCUH8="
  [mod."golang.org/x/oauth2"]
    version = "v0.30.0"
    hash = "sha256-btD7BUtQpOswusZY5qIU90uDo38buVrQ0tmmQ8qNHDg="
  [mod."golang.org/x/sync"]
    version = "v0.14.0"
    hash = "sha256-YNQLeFMeXN9y0z4OyXV/LJ4hA54q+ljm1ytcy80O6r4="
  [mod."golang.org/x/sys"]
    version = "v0.33.0"
    hash = "sha256-wlOzIOUgAiGAtdzhW/KPl/yUVSH/lvFZfs5XOuJ9LOQ="
  [mod."golang.org/x/term"]
    version = "v0.32.0"
    hash = "sha256-4cM/vhb8EUrlfHidBRfjYEQlUQehXiydJN77YkQvAic="
  [mod."golang.org/x/text"]
    version = "v0.25.0"
    hash = "sha256-gkOd4CuWr7OfCEk2EZ8KG5t9NRG7bM9Zj/lpv3y28yg="
  [mod."golang.org/x/time"]
    version = "v0.11.0"
    hash = "sha256-ImTej/e5iUHbWPZMA4M2GYbsbiiZQxIrgcnYsc7uD68="
  [mod."golang.org/x/tools"]
    version = "v0.33.0"
    hash = "sha256-OcjT9lh/nxGS2/rElTu5yNE2cXa1fUzRlyl+yZ36b4Q="
  [mod."golang.zx2c4.com/wintun"]
    version = "v0.0.0-20230126152724-0fa3db229ce2"
    hash = "sha256-cjMLNjKnnupVROWmeASORVieAL9ieYdzX3cFzG8bCpo="
  [mod."golang.zx2c4.com/wireguard/windows"]
    version = "v0.5.3"
    hash = "sha256-wcJWS/4Fqbc+1RHSntex0zBdlHiZfzrea4QabYkNKvU="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."gvisor.dev/gvisor"]
    version = "v0.0.0-20250205023644-9414b50a5633"
    hash = "sha256-XX3uGywgI/ihUyaGs3VbvoOayJBrGGKPZtO+KBZlCm8="
  [mod."tailscale.com"]
    version = "v1.88.2"
    hash = "sha256-nme+jRSLenRG3Ok3xcmcwW4vuJbI0rGLurRntd0rMP0="
